# Generated by Powerlevel10k configuration wizard
# Basic settings for a customized prompt with AWS, Kubernetes and Git info

# Enable elements on the prompt
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  # Line 1
  os_icon                 # OS identifier
  dir                     # Current directory
  vcs                     # Git status
  # Line 2
  newline                 # \n
  prompt_char             # Prompt symbol
)

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status                  # Exit code of the last command
  command_execution_time  # Duration of the last command
  background_jobs         # Presence of background jobs
  direnv                  # direnv status
  asdf                    # asdf version manager
  virtualenv              # Python virtual environment
  aws                     # AWS profile
  kubecontext             # Current Kubernetes context
  context                 # User@hostname
  time                    # Current time
  newline                 # \n
)

# AWS settings
POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|awless|terraform|pulumi|terragrunt'
POWERLEVEL9K_AWS_CLASSES=(
  '*prod*' PROD
  '*staging*' STAGING
  '*' DEFAULT
)
POWERLEVEL9K_AWS_PROD_BACKGROUND=red
POWERLEVEL9K_AWS_STAGING_BACKGROUND=208
POWERLEVEL9K_AWS_DEFAULT_BACKGROUND=blue

# Kubernetes settings
POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern|kubeseal|skaffold|kubent|kubecolor|cmctl|sparkctl'
POWERLEVEL9K_KUBECONTEXT_CLASSES=(
  '*prod*' PROD
  '*staging*' STAGING
  '*' DEFAULT
)
POWERLEVEL9K_KUBECONTEXT_PROD_BACKGROUND=red
POWERLEVEL9K_KUBECONTEXT_STAGING_BACKGROUND=208
POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND=blue

# Git settings
POWERLEVEL9K_VCS_BRANCH_ICON='\uE725 '
POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

# General settings
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT='❯'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT='❯'
POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_CONTENT='❮'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_CONTENT='❮'

# Directory settings
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_DIR_SHOW_WRITABLE=true

# Other segment settings
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2

# Instant prompt mode
POWERLEVEL9K_INSTANT_PROMPT=verbose

# Add extra newline before each prompt
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# Set color scheme
POWERLEVEL9K_COLOR_SCHEME='dark'

# Fix spacing
ZLE_RPROMPT_INDENT=0

# Default font (should be patched with proper icons)
POWERLEVEL9K_MODE='nerdfont-complete'
